spring:
  flyway:
    enabled: false

#  & 'C:\Program Files\Java\jdk-18.0.1.1\bin\keytool.exe' -genkeypair -alias selfsigned
#  -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 365 -storetype PKCS12
#  -dname "CN=Roman Galyaminskiy, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown" -storepass storepass

server:
  port: 8443
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: storepass
    key-alias: selfsigned
